path_to_dataset = "data/processed_data" # Path to dataset

shift = 48 # Integer with the lag

[which_scalers]
features = "minmax" # Scaler to use, currently "minmax" and "standard" are supported
targets = "minmax" # Scaler to use, currently "minmax" and "standard" are supported

[qf_params]
[qf_params.kf_params]
n_splits = 10
random_state = false
[qf_params.rfqr_params]
random_state = false
min_samples_split = 25
n_estimators = 1000
n_jobs = -1